# 0-2: Numpy

빠른 수치 연산을 위한 Numpy 기초를 학습합니다.

## 학습 목표
1. Numpy 배열 생성 및 속성 이해
2. 인덱싱과 슬라이싱
3. 집계 연산 (sum, mean, std)
4. 조건 필터링
5. 브로드캐스팅

In [1]:
import numpy as np
print(f"numpy version: {np.__version__}")

numpy version: 2.3.5


---
## 1. Numpy란?

### 📚 왜 Numpy를 쓰는가?

- **빠름**: C로 구현, 벡터 연산
- **메모리 효율**: 동일 타입만 저장
- **ML 필수**: sklearn, pandas 모두 numpy 기반

In [6]:
# 리스트 vs numpy 속도 비교
import time

size = 1000000
py_list = list(range(size))
np_arr = np.arange(size)

# 리스트 연산
start = time.time()
result = [x * 2 for x in py_list]
print(f"리스트: {time.time() - start:.4f}초")

# numpy 연산
start = time.time()
result = np_arr * 2
print(f"numpy:  {time.time() - start:.4f}초")

리스트: 0.0382초
numpy:  0.0080초


---
## 2. 배열 생성

In [7]:
# 📚 배열 생성 방법

# 리스트로 생성
arr1 = np.array([1, 2, 3, 4, 5])
print("array:", arr1)

# 특수 배열
zeros = np.zeros(5)
ones = np.ones(5)
print("zeros:", zeros)
print("ones:", ones)

# 범위 배열
arange = np.arange(0, 10, 2)  # 0부터 10까지 2씩
print("arange:", arange)

array: [1 2 3 4 5]
zeros: [0. 0. 0. 0. 0.]
ones: [1. 1. 1. 1. 1.]
arange: [0 2 4 6 8]


In [8]:
# 📚 배열 속성
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("배열:")
print(arr)
print(f"shape: {arr.shape}")  # (행, 열)
print(f"dtype: {arr.dtype}")  # 데이터 타입
print(f"ndim:  {arr.ndim}")   # 차원 수

배열:
[[1 2 3]
 [4 5 6]]
shape: (2, 3)
dtype: int64
ndim:  2


### 💻 실습 1: 배열 생성

1. 1부터 10까지 정수 배열 생성
2. 3x3 영행렬(zeros) 생성
3. 0부터 100까지 10씩 증가하는 배열 생성

In [19]:
# 💻 실습 1

# TODO: 1부터 10까지 정수 배열
arr1 = np.arange(1,11)

# TODO: 3x3 영행렬
arr2 = np.zeros((3,3))

# TODO: 0, 10, 20, ..., 100
arr3 = np.arange(0,101,10)

print("arr1:", arr1)
print("arr2 shape:", arr2.shape if arr2 is not None else None)
print("arr3:", arr3)

arr1: [ 1  2  3  4  5  6  7  8  9 10]
arr2 shape: (3, 3)
arr3: [  0  10  20  30  40  50  60  70  80  90 100]


In [20]:
# 체크포인트 1
assert list(arr1) == [1,2,3,4,5,6,7,8,9,10], "arr1: 1~10 배열"
assert arr2.shape == (3, 3), "arr2: 3x3 shape"
assert list(arr3) == [0,10,20,30,40,50,60,70,80,90,100], "arr3: 0~100 (10씩)"

print("✅ 체크포인트 1 통과!")

✅ 체크포인트 1 통과!


---
## 3. 인덱싱과 슬라이싱

In [21]:
# 📚 1차원 인덱싱
arr = np.array([10, 20, 30, 40, 50])

print("arr[0]:", arr[0])      # 첫 번째
print("arr[-1]:", arr[-1])    # 마지막
print("arr[1:3]:", arr[1:3])  # 슬라이싱

arr[0]: 10
arr[-1]: 50
arr[1:3]: [20 30]


In [22]:
# 📚 2차원 인덱싱
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("전체:")
print(arr2d)
print()
print("arr2d[0, 1]:", arr2d[0, 1])   # 0행 1열
print("arr2d[1]:", arr2d[1])          # 1행 전체
print("arr2d[:, 0]:", arr2d[:, 0])    # 0열 전체
print("arr2d[:2, :2]:")               # 2x2 부분
print(arr2d[:2, :2])

전체:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2d[0, 1]: 2
arr2d[1]: [4 5 6]
arr2d[:, 0]: [1 4 7]
arr2d[:2, :2]:
[[1 2]
 [4 5]]


### 💻 실습 2: 인덱싱

아래 배열에서 지정된 값을 추출하세요.

In [26]:
# 💻 실습 2
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

# TODO: 50 추출 (1행 1열)
val1 = data[1,1]

# TODO: 마지막 행 전체 [70, 80, 90]
val2 = data[2]

# TODO: 두 번째 열 전체 [20, 50, 80]
val3 = data[:,1]

print("val1:", val1)
print("val2:", val2)
print("val3:", val3)

val1: 50
val2: [70 80 90]
val3: [20 50 80]


In [27]:
# 체크포인트 2
assert val1 == 50, "val1은 50"
assert list(val2) == [70, 80, 90], "val2는 마지막 행"
assert list(val3) == [20, 50, 80], "val3는 두 번째 열"

print("✅ 체크포인트 2 통과!")

✅ 체크포인트 2 통과!


---
## 4. 연산

In [28]:
# 📚 집계 연산
arr = np.array([10, 20, 30, 40, 50])

print(f"sum:  {arr.sum()}")   # 합계
print(f"mean: {arr.mean()}") # 평균
print(f"std:  {arr.std()}")  # 표준편차
print(f"max:  {arr.max()}")  # 최대
print(f"min:  {arr.min()}")  # 최소

sum:  150
mean: 30.0
std:  14.142135623730951
max:  50
min:  10


In [31]:
# 📚 axis 개념 (2차원)
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

print("전체:")
print(arr2d)
print()
print(f"전체 합: {arr2d.sum()}")           # 21
print(f"행별 합 (axis=1): {arr2d.sum(axis=1)}")  # [6, 15]
print(f"열별 합 (axis=0): {arr2d.sum(axis=0)}")  # [5, 7, 9]

전체:
[[1 2 3]
 [4 5 6]]

전체 합: 21
행별 합 (axis=1): [ 6 15]
열별 합 (axis=0): [5 7 9]


### 💻 실습 3: 집계 연산

거래 금액 데이터의 통계를 계산하세요.

In [33]:
# 💻 실습 3
amounts = np.array([15000, 3200, 89000, 4500, 120000, 7800, 55000])

# TODO: 총 거래액
total = amounts.sum()

# TODO: 평균 거래액
avg = amounts.mean()

# TODO: 최대 거래액
max_amt = amounts.max()

print(f"총 거래액: {total:,}원")
print(f"평균 거래액: {avg:,.0f}원")
print(f"최대 거래액: {max_amt:,}원")

총 거래액: 294,500원
평균 거래액: 42,071원
최대 거래액: 120,000원


In [34]:
# 체크포인트 3
assert total == 294500, "총 거래액"
assert avg == 42071.428571428572, "평균 거래액"
assert max_amt == 120000, "최대 거래액"

print("✅ 체크포인트 3 통과!")

✅ 체크포인트 3 통과!


---
## 5. 조건 필터링

In [35]:
# 📚 불리언 배열
arr = np.array([10, 25, 30, 5, 40])

# 조건 적용 → 불리언 배열
mask = arr > 20
print("arr > 20:", mask)  # [False, True, True, False, True]

# 불리언으로 필터링
filtered = arr[mask]
print("필터링:", filtered)  # [25, 30, 40]

arr > 20: [False  True  True False  True]
필터링: [25 30 40]


In [36]:
# 📚 np.where
arr = np.array([10, 25, 30, 5, 40])

# 조건에 따라 값 변경
result = np.where(arr > 20, "high", "low")
print(result)  # ['low', 'high', 'high', 'low', 'high']

['low' 'high' 'high' 'low' 'high']


### 💻 실습 4: 조건 필터링 (사기 거래 찾기)

100,000원 이상 거래를 고액 거래로 분류하세요.

In [40]:
# 💻 실습 4
transactions = np.array([15000, 250000, 8900, 120000, 45000, 980000, 3200])

# TODO: 100,000원 이상인 거래만 필터링
high_value = transactions[transactions >= 100000]

# TODO: 고액 거래 개수
high_count = len(high_value)

# TODO: np.where로 "고액"/"일반" 라벨링
labels = np.where(transactions >= 100000, "고액", "일반")

print("고액 거래:", high_value)
print("고액 거래 수:", high_count)
print("라벨:", labels)

고액 거래: [250000 120000 980000]
고액 거래 수: 3
라벨: ['일반' '고액' '일반' '고액' '일반' '고액' '일반']


In [41]:
# 체크포인트 4
assert list(high_value) == [250000, 120000, 980000], "고액 거래"
assert high_count == 3, "고액 거래 수"
assert list(labels) == ["일반", "고액", "일반", "고액", "일반", "고액", "일반"], "라벨"

print("✅ 체크포인트 4 통과!")

✅ 체크포인트 4 통과!


---
## 6. 브로드캐스팅

In [42]:
# 📚 브로드캐스팅
# 스칼라 연산이 전체 배열에 적용됨

arr = np.array([10, 20, 30, 40, 50])

print("원본:", arr)
print("* 2:", arr * 2)
print("+ 5:", arr + 5)
print("/ 10:", arr / 10)

원본: [10 20 30 40 50]
* 2: [ 20  40  60  80 100]
+ 5: [15 25 35 45 55]
/ 10: [1. 2. 3. 4. 5.]


In [43]:
# 📚 정규화 예시 (Min-Max Scaling)
# (x - min) / (max - min) → 0~1 범위로 변환

data = np.array([100, 200, 300, 400, 500])

min_val = data.min()
max_val = data.max()
normalized = (data - min_val) / (max_val - min_val)

print("원본:", data)
print("정규화:", normalized)

원본: [100 200 300 400 500]
정규화: [0.   0.25 0.5  0.75 1.  ]


### 💻 실습 5: 정규화

거래 금액을 0~1 범위로 정규화하세요.

In [44]:
# 💻 실습 5
amounts = np.array([10000, 50000, 30000, 80000, 20000])

# TODO: Min-Max 정규화 (0~1)
normalized = (amounts - amounts.min()) / (amounts.max() - amounts.min())

print("원본:", amounts)
print("정규화:", normalized)

원본: [10000 50000 30000 80000 20000]
정규화: [0.         0.57142857 0.28571429 1.         0.14285714]


In [45]:
# 체크포인트 5
expected = np.array([0.0, 0.571, 0.286, 1.0, 0.143])
assert np.allclose(normalized, expected, atol=0.01), "정규화 결과"

print("✅ 체크포인트 5 통과!")

✅ 체크포인트 5 통과!


---
## ✅ 최종 체크포인트

In [46]:
print("="*50)
print("🎉 0-2 완료: Numpy")
print("="*50)
print()
print("배운 것:")
print("  - 배열 생성: np.array, zeros, ones, arange")
print("  - 인덱싱: arr[0], arr[0, 1], arr[:, 0]")
print("  - 집계: sum, mean, std, max, min")
print("  - 조건 필터링: arr[arr > 0], np.where")
print("  - 브로드캐스팅: 스칼라 연산, 정규화")
print()
print("다음: 0-3 Pandas")

🎉 0-2 완료: Numpy

배운 것:
  - 배열 생성: np.array, zeros, ones, arange
  - 인덱싱: arr[0], arr[0, 1], arr[:, 0]
  - 집계: sum, mean, std, max, min
  - 조건 필터링: arr[arr > 0], np.where
  - 브로드캐스팅: 스칼라 연산, 정규화

다음: 0-3 Pandas
